---
title: "Project"
output: word_document
date: "2023-03-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#loading the data
setwd("C:/Users/Icy/Documents/School-GMU/BINF 702/Project files")
Ach_data <- read.csv("acetylcholinesterase_05_bioactivity_data_2class_pIC50.csv")

head(Ach_data)
```


```{r}
#test data for normality
Ach_norm<-rnorm(100)
shapiro.test(Ach_norm) # we cannot reject the hypothesis that the data is normally distributed
```

```{r}
#Create a frequency plot of the 2 bioactivity classes
library(rlang)
library(ggplot2)

ggplot(Ach_data, aes(x = class)) +
  geom_bar(color = "black", fill = "lightblue") +
  labs(x = "Bioactivity class", y = "Frequency") +
  theme_classic() +
  theme(axis.text = element_text(size = 14, face = "bold"),
        axis.title = element_text(size = 14, face = "bold"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = "none")
```


```{r}
#scatterplot of MW versus logP

ggplot(Ach_data, aes(x=MW, y=LogP, color=class, size=0.5)) + 
  geom_point(alpha=0.7, shape=1, aes(fill=class), show.legend=TRUE, stroke=0.5) + 
  scale_size_continuous(range = c(2,10)) +
  labs(x = "MW", y = "LogP") +
  theme_bw() +
  theme(legend.position = c(0.02,0.98), legend.justification = c(0, 1), legend.background = element_blank(), legend.key.width = unit(0.8,"cm"))


```

```{r}
#box plots of pIC50 values versus bioactivity class

ggplot(data=Ach_data, aes(x=class, y=pIC50,fill=class)) +
  geom_boxplot() +
  scale_fill_manual(values=c("blue", "red")) +
  labs(x="Bioactivity class", y="pIC50 value") +
  theme_classic() +
  theme(axis.text.x = element_text(angle=90, vjust=0.5, hjust=1), 
        legend.position="none")

```

```{r}
#mannwhitney U test. Non parametric stat significant tests

mannwhitney <- function(descriptor, verbose=FALSE) {
  # actives and inactives
  active <- Ach_data[Ach_data$class == "active", descriptor]
  inactive <- Ach_data[Ach_data$class == "inactive", descriptor]

  # compare samples
  res <- wilcox.test(active, inactive)

  # interpret
  alpha <- 0.05
  if (res$p.value > alpha) {
    interpretation <- "Same distribution (fail to reject H0)"
  } else {
    interpretation <- "Different distribution (reject H0)"
  }

  # print results
  if (verbose) {
    cat(paste("Descriptor:", descriptor, "\n"))
    cat(paste("Statistics:", res$statistic, "\n"))
    cat(paste("p-value:", res$p.value, "\n"))
    cat(paste("alpha:", alpha, "\n"))
    cat(paste("Interpretation:", interpretation, "\n"))
  }


  # return results
  return(data.frame(Descriptor=descriptor, Statistics=res$statistic,
                     p=res$p.value, alpha=alpha,
                     Interpretation=interpretation))
}


mannwhitney("pIC50")
```


```{r}
#MW boxplot versus bioactivity class
ggplot(data=Ach_data, aes(x=class, y=MW,fill=class)) +
  geom_boxplot() +
  scale_fill_manual(values=c("blue", "red")) +
  labs(x="Bioactivity class", y="MW value") +
  theme_classic() +
  theme(axis.text.x = element_text(angle=90, vjust=0.5, hjust=1), 
        legend.position="none")

```
```{r}
#mannwhitney test in MW

mannwhitney("MW")
```

```{r}
#boxplot of logP versus bioactivity class
ggplot(data=Ach_data, aes(x=class, y=LogP,fill=class)) +
  geom_boxplot() +
  scale_fill_manual(values=c("blue", "red")) +
  labs(x="Bioactivity class", y="LogP value") +
  theme_classic() +
  theme(axis.text.x = element_text(angle=90, vjust=0.5, hjust=1), 
        legend.position="none")

```
```{r}
#mannwhitney test in LogP

mannwhitney("LogP")
```

```{r}
#Now looking at NumH donors versus bioactivity class
ggplot(data=Ach_data, aes(x=class, y=NumHDonors,fill=class)) +
  geom_boxplot() +
  scale_fill_manual(values=c("blue", "red")) +
  labs(x="Bioactivity class", y="NumHDonors value") +
  theme_classic() +
  theme(axis.text.x = element_text(angle=90, vjust=0.5, hjust=1), 
        legend.position="none")

```
```{r}
#mannwhitney test on NumHdonors 

mannwhitney("NumHDonors")

```
```{r}
#NumHAcceptors
ggplot(data=Ach_data, aes(x=class, y=NumHAcceptors,fill=class)) +
  geom_boxplot() +
  scale_fill_manual(values=c("blue", "red")) +
  labs(x="Bioactivity class", y="NumHAcceptors value") +
  theme_classic() +
  theme(axis.text.x = element_text(angle=90, vjust=0.5, hjust=1), 
        legend.position="none")

```
```{r}
#mannwhitney test on NumHAcceptors
mannwhitney("NumHAcceptors")
```

